image: Visual Studio 2019

environment:
  UmbPackKey:
    secure: Y/76f3rkb4wyNyny/hPXqxyFyn1ttDUgCyKHKTEn8qUBP/GtRdZqD+bG5u4nhlccD1700FfRJsZgUp1qjRWKx8H4PsXmaRKklwJJ2fs4P+k=
  
cache:
  - '%APPDATA%\npm-cache'
  - '%LocalAppData%\NuGet\v3-cache'

install:
  - cmd: npm install --global parcel-bundler
  - cmd: dotnet tool install --global Umbraco.Tools.Packages

platform: Any CPU
configuration: Release

before_build:
  - nuget restore

build:
  parallel: true

test: off

artifacts:
  - path: '**\bin\$(configuration)\*.nupkg'
  - path: '**\bin\$(configuration)\*.snupkg'
  - path: '**\bin\$(configuration)\*.zip'

deploy:
  - provider: NuGet
    api_key:
      secure: 3rS8SSsTr0VHNAkG7ayAvic+yEedX8IIKq9QwaNrtLYDzgpyZJjY1mLuBYDZF0Qj
    on:
        APPVEYOR_REPO_TAG: true

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: ''
    auth_token:
        secure: Otbl8p8qCwciDqJgSWCyN0Arfs5XS1CwiHcK+r0F6uz9Rxt4gzBFvlc3cjPV3NxR
    on:
        APPVEYOR_REPO_TAG: true

after_deploy:
  - ps: |
      # Ensure we only push on tagged builds
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        foreach ($artifactName in $artifacts.keys) {
          $path = $artifacts[$artifactName].path
          # Only push the NestingContently Umbraco package
          if ($path -match "Nesting_Contently_[0-9.]+\.zip$") {
            umbpack push $path -k $env:UmbPackKey -a current
          }
        }
      }