image: Visual Studio 2019

cache:
  - packages -> **\packages.config
  - '%APPDATA%\npm-cache'
  
install:
  - cmd: npm install --global parcel-bundler
  - cmd: dotnet tool install --global Umbraco.Tools.Packages

platform: Any CPU
configuration: Release

before_build:
  - nuget restore

build:
  parallel: true

test: off

artifacts:
  - path: '**\bin\$(configuration)\*.nupkg'
  - path: '**\bin\$(configuration)\*.snupkg'
  - path: '**\bin\$(configuration)\*.zip'

deploy:
  - provider: NuGet
    api_key:
      secure: 3rS8SSsTr0VHNAkG7ayAvic+yEedX8IIKq9QwaNrtLYDzgpyZJjY1mLuBYDZF0Qj
    on:
        APPVEYOR_REPO_TAG: true

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
        secure: Otbl8p8qCwciDqJgSWCyN0Arfs5XS1CwiHcK+r0F6uz9Rxt4gzBFvlc3cjPV3NxR
    on:
        APPVEYOR_REPO_TAG: true