name: .NET

on:
  push:
    branches: [ v9/dev ]
  pull_request:
    branches: [ v9/dev ]

jobs:
  web:
    name: Build app_plugin
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM dependencies
      run: npm ci --prefer-offline
    - name: Publish
      run: npm run publish
      
  converters:
    name: Build ValueConverters
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
