name: Release

on:
  push:
    tags:
      - 'v9*'

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: |
        mkdir __out
        dotnet pack -c Release -o __out --no-restore
        dotnet nuget push ./__out/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{secrets.NUGET_TOKEN}}
        rm -r -force __out
